import { SuperagentTaskResult } from "./superagent";
import { EmployeeTask } from "@shared/schema";
import { Octokit } from "@octokit/rest";

export async function deliverTaskResult(task: EmployeeTask, result: SuperagentTaskResult) {
  console.log(`[delivery] Delivering result for task ${task.id} (source: ${task.source})`);
  
  if (task.source === "slack" && process.env.SLACK_NOTIFY_WEBHOOK) {
    try {
      await fetch(process.env.SLACK_NOTIFY_WEBHOOK, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          text: `*Task Completed*: ${task.goal}\n*Summary*: ${result.summary}`
        })
      });
    } catch (err) {
      console.error(`[delivery] Failed to notify Slack:`, err);
    }
  }

  // GitHub integration
  if (task.source === "github" && process.env.GITHUB_TOKEN && task.sourceId) {
    // sourceId format expected: "owner/repo" or "owner/repo#issueNumber"
    try {
      const [repoPart, issuePart] = task.sourceId.split("#");
      const [owner, repo] = repoPart.split("/");
      
      if (owner && repo && result.files && result.files.length > 0) {
        console.log(`[delivery] Pushing ${result.files.length} files to GitHub repo ${owner}/${repo}`);
        const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
        
        // 1. Get latest commit on main
        const { data: refData } = await octokit.git.getRef({
          owner, repo, ref: "heads/main"
        });
        const latestCommitSha = refData.object.sha;
        
        // 2. Get the base tree
        const { data: commitData } = await octokit.git.getCommit({
          owner, repo, commit_sha: latestCommitSha
        });
        const baseTreeSha = commitData.tree.sha;
        
        // 3. Create blobs & tree entries for each file
        const tree = await Promise.all(result.files.map(async (file: any) => {
          return {
            path: file.path.replace(/^\//, ""), // remove leading slash if any
            mode: "100644",
            type: "blob" as const,
            content: file.content
          };
        }));
        
        // 4. Create new tree
        const { data: newTree } = await octokit.git.createTree({
          owner, repo, tree, base_tree: baseTreeSha
        });
        
        // 5. Create new commit
        const { data: newCommit } = await octokit.git.createCommit({
          owner, repo,
          message: `Auto-generated by AI Employee: ${task.goal.split("\\n")[0].substring(0, 50)}`,
          tree: newTree.sha,
          parents: [latestCommitSha]
        });
        
        // 6. Create a new branch
        const branchName = `ai-employee/task-${task.id}-${Date.now()}`;
        await octokit.git.createRef({
          owner, repo,
          ref: `refs/heads/${branchName}`,
          sha: newCommit.sha
        });
        
        // 7. Create Pull Request
        const title = `AI Employee: ${task.goal.split("\\n")[0].substring(0, 50)}...`;
        const body = `Automated resolution for task: \n\n> ${task.goal}\n\n### Summary\n${result.summary}`;
        
        const { data: pr } = await octokit.pulls.create({
          owner, repo,
          title,
          body,
          head: branchName,
          base: "main"
        });
        
        console.log(`[delivery] Successfully created PR: ${pr.html_url}`);
      } else if (result.output && issuePart) {
        // If no files but it's an issue response, post a comment
        const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
        await octokit.issues.createComment({
          owner, repo,
          issue_number: parseInt(issuePart),
          body: `🤖 **AI Employee Response**\n\n${result.output}\n\n*Summary: ${result.summary}*`
        });
        console.log(`[delivery] Successfully commented on issue #${issuePart}`);
      }
    } catch (err: any) {
      console.error(`[delivery] Failed to deliver to GitHub:`, err);
    }
  }
  
  return true;
}
